version: '3'

services:
  backend:
    build: ./backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000

  frontend:
    build: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
