version: '3'

services:
  backend:
    image: node:latest
    working_dir: /app/
    command: ./start
    volumes:
      - ./backend/:/app/
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 4000:4000

  frontend:
    image: node:latest
    working_dir: /app/
    command: ./start
    volumes:
      - ./frontend/:/app/
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
